import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export const languages = [
  { code: 'en', label: 'English', shortLabel: 'EN' },
  { code: 'am', label: 'አማርኛ', shortLabel: 'አማ' },
  { code: 'om', label: 'Afaan Oromo', shortLabel: 'OM' },
];

const translations = {
  en: {
    language: 'Language',
    navHome: 'Home',
    navMarketplace: 'Marketplace',
    navCoach: 'AI Coach',
    navWellness: 'Wellness',
    navFarmer: 'Farmer',
    navProfile: 'Profile',
    cart: 'Cart',
    profile: 'Profile',
    menu: 'Menu',
    saveProduct: 'Save product',
    byFarmer: 'by {name}',
    addToCart: 'Add to cart',
    categoryGrain: 'Grain',
    categoryVegetable: 'Vegetable',
    categoryLegume: 'Legume',
    categoryFruit: 'Fruit',
    categoryPantry: 'Pantry',
    trustExcellent: 'excellent',
    trustStrong: 'strong',
    trustReview: 'review',
    freshExcellent: 'fresh',
    freshGood: 'good',
    freshFair: 'fair',
    landingBadge: 'Farm-to-wellness marketplace',
    landingCopy: 'Connect directly with Ethiopian smallholder farmers and get AI nutrition recommendations based on fresh, local food near you.',
    shopFreshFood: 'Shop fresh food',
    askAiCoach: 'Ask AI coach',
    wellnessHub: 'Wellness hub',
    statProducts: '30 products',
    statFarmers: '10 farmers',
    statDiscovery: '20 km discovery',
    todayNear: 'Today near Addis Ababa',
    harvestHero: 'Teff, spinach, lentils and honey harvested within 48 hours.',
    browseNearby: 'Browse nearby',
    aiNutrition: 'AI nutrition',
    verifiedFarmers: 'Verified farmers',
    impactMetrics: 'Impact metrics',
    workflowCopy: 'A practical workflow for healthier households and stronger farmer income.',
    advancedWellness: 'Advanced wellness',
    wellnessHeadline: 'Mood, pregnancy, and mindfulness now inform food recommendations',
    openDashboard: 'Open dashboard',
    liveMarketplace: 'Live marketplace',
    freshPicks: 'Fresh picks for the demo',
    viewAll: 'View all',
    valueFarmers: 'Farmers keep more value by selling direct.',
    valueConsumers: 'Consumers see freshness, distance, and trust before buying.',
    valueNutrition: 'Nutrition guidance turns local crops into wellness plans.',
    marketplaceEyebrow: 'Location-based discovery',
    filters: 'Filters',
    search: 'Search',
    searchPlaceholder: 'Teff, honey...',
    category: 'Category',
    all: 'All',
    withinKm: 'Within {distance} km',
    freshness: 'Freshness {freshness}+',
    maxPrice: 'Max price {price} ETB',
    productsFound: '{count} products found',
    simulatedLocation: 'Simulated location: Addis Ababa',
    cartEmpty: 'Your cart is empty.',
    browseMarketplace: 'Browse marketplace',
    orderSummary: 'Order summary',
    subtotal: 'Subtotal',
    delivery: 'Delivery',
    total: 'Total',
    checkout: 'Checkout',
    paymentSuccessful: 'Payment Successful',
    orderConfirmed: 'Order Confirmed: {id}',
    viewProfile: 'View profile',
    mockPayment: 'Mock payment',
    mockPaymentCopy: 'No real payment integration. Hackathon demo flow only.',
    payConfirm: 'Pay and confirm order',
    backMarketplace: 'Back to marketplace',
    perUnit: '{price} ETB per {unit}',
    freshnessDetail: 'Freshness {score}: {label}',
    trustDetail: 'Trust {score}: {label}',
    harvested: 'Harvested {date}',
    kmAway: '{distance} km away',
    nutritionFacts: 'Nutrition facts',
    wellnessScore: 'Wellness score {score}',
    shopAgain: 'Shop again',
    unifiedWellnessProfile: 'Unified wellness profile',
    profileWellnessHeadline: 'Nutrition, mood, pregnancy, breathing, activity, and freshness are connected.',
    viewDashboard: 'View dashboard',
    orders: 'Orders',
    savedProducts: 'Saved products',
    noSavedProducts: 'No saved products yet.',
    wellnessTitle: 'How are you feeling today?',
    wellnessCopy: 'Track mood, pregnancy wellness, and breathing in one simple place.',
    moodCheckIn: 'Mood Check-In',
    pregnancyCoach: 'Pregnancy Coach',
    breathing: 'Breathing',
    myWellness: 'My Wellness',
    energy: 'Energy',
    sleep: 'Sleep',
    stress: 'Stress',
    moodNote: 'Write a short note about your day...',
    saveMood: 'Save mood',
    currentWeek: 'Current week',
    week: 'Week {week}',
    dueDate: 'Due date',
    waterToday: 'Water today',
    ironToday: 'Iron today',
    todaysGuidance: "Today's guidance",
    pregnancyGuidance: 'Eat iron-rich foods, drink water, take a gentle walk if cleared, and avoid unsafe foods.',
    logPregnancy: 'Log pregnancy update',
    recommendedNow: 'Recommended now:',
    streak: 'Streak',
    lastSession: 'Last session',
    stressReduced: 'Stress reduced',
    unifiedWellnessScore: 'Unified Wellness Score',
    wellnessScoreParts: 'Nutrition + mood + pregnancy + breathing + freshness',
    aiSuggestion: 'AI suggestion',
    mood: 'Mood',
    viewHistory: 'View history',
    getAiAdvice: 'Get AI advice',
    shopWellnessFoods: 'Shop wellness foods',
  },
  am: {
    language: 'ቋንቋ',
    navHome: 'መነሻ',
    navMarketplace: 'ገበያ',
    navCoach: 'AI አማካሪ',
    navWellness: 'ጤና',
    navFarmer: 'አርሶ አደር',
    navProfile: 'መገለጫ',
    cart: 'ጋሪ',
    profile: 'መገለጫ',
    menu: 'ምናሌ',
    saveProduct: 'ምርት አስቀምጥ',
    byFarmer: 'በ {name}',
    addToCart: 'ወደ ጋሪ ጨምር',
    categoryGrain: 'እህል',
    categoryVegetable: 'አትክልት',
    categoryLegume: 'ጥራጥሬ',
    categoryFruit: 'ፍሬ',
    categoryPantry: 'የቤት እቃ',
    trustExcellent: 'በጣም ጥሩ',
    trustStrong: 'ጠንካራ',
    trustReview: 'ይገመገም',
    freshExcellent: 'ትኩስ',
    freshGood: 'ጥሩ',
    freshFair: 'መካከለኛ',
    landingBadge: 'ከእርሻ ወደ ጤና ገበያ',
    landingCopy: 'ከኢትዮጵያ አነስተኛ አርሶ አደሮች ጋር በቀጥታ ይገናኙ፣ በአቅራቢያዎ ባለ ትኩስ የአካባቢ ምግብ ላይ የተመሰረተ የAI የምግብ ምክር ያግኙ።',
    shopFreshFood: 'ትኩስ ምግብ ይግዙ',
    askAiCoach: 'AI አማካሪን ይጠይቁ',
    wellnessHub: 'የጤና ማዕከል',
    statProducts: '30 ምርቶች',
    statFarmers: '10 አርሶ አደሮች',
    statDiscovery: '20 ኪ.ሜ ፍለጋ',
    todayNear: 'ዛሬ በአዲስ አበባ አቅራቢያ',
    harvestHero: 'ጤፍ፣ ስፒናች፣ ምስር እና ማር በ48 ሰዓት ውስጥ ተሰብስበዋል።',
    browseNearby: 'አቅራቢያ ይመልከቱ',
    aiNutrition: 'AI የምግብ ምክር',
    verifiedFarmers: 'የተረጋገጡ አርሶ አደሮች',
    impactMetrics: 'የተፅዕኖ መለኪያዎች',
    workflowCopy: 'ለጤናማ ቤተሰቦች እና ለጠንካራ የአርሶ አደር ገቢ ተግባራዊ አሰራር።',
    advancedWellness: 'የላቀ ጤና',
    wellnessHeadline: 'ስሜት፣ እርግዝና እና የአእምሮ ልምምድ አሁን የምግብ ምክሮችን ያበረታታሉ',
    openDashboard: 'ዳሽቦርድ ክፈት',
    liveMarketplace: 'ቀጥታ ገበያ',
    freshPicks: 'ለሙከራው ትኩስ ምርጫዎች',
    viewAll: 'ሁሉንም ይመልከቱ',
    valueFarmers: 'አርሶ አደሮች በቀጥታ በመሸጥ ተጨማሪ ዋጋ ያገኛሉ።',
    valueConsumers: 'ገዢዎች ከመግዛት በፊት ትኩስነት፣ ርቀት እና እምነት ያያሉ።',
    valueNutrition: 'የምግብ ምክር የአካባቢ ሰብሎችን ወደ የጤና እቅዶች ይቀይራል።',
    marketplaceEyebrow: 'በአካባቢ ላይ የተመሰረተ ፍለጋ',
    filters: 'ማጣሪያዎች',
    search: 'ፈልግ',
    searchPlaceholder: 'ጤፍ፣ ማር...',
    category: 'ምድብ',
    all: 'ሁሉም',
    withinKm: 'በ {distance} ኪ.ሜ ውስጥ',
    freshness: 'ትኩስነት {freshness}+',
    maxPrice: 'ከፍተኛ ዋጋ {price} ETB',
    productsFound: '{count} ምርቶች ተገኙ',
    simulatedLocation: 'የተመሰለ ቦታ፦ አዲስ አበባ',
    cartEmpty: 'ጋሪዎ ባዶ ነው።',
    browseMarketplace: 'ገበያውን ይመልከቱ',
    orderSummary: 'የትዕዛዝ ማጠቃለያ',
    subtotal: 'ንዑስ ድምር',
    delivery: 'መድረሻ',
    total: 'ጠቅላላ',
    checkout: 'ክፍያ',
    paymentSuccessful: 'ክፍያው ተሳክቷል',
    orderConfirmed: 'ትዕዛዝ ተረጋግጧል፦ {id}',
    viewProfile: 'መገለጫ ይመልከቱ',
    mockPayment: 'የሙከራ ክፍያ',
    mockPaymentCopy: 'እውነተኛ የክፍያ ግንኙነት የለም። ለሃካቶን ሙከራ ብቻ።',
    payConfirm: 'ክፈል እና ትዕዛዝ አረጋግጥ',
    backMarketplace: 'ወደ ገበያ ተመለስ',
    perUnit: '{price} ETB በ {unit}',
    freshnessDetail: 'ትኩስነት {score}: {label}',
    trustDetail: 'እምነት {score}: {label}',
    harvested: 'የተሰበሰበበት {date}',
    kmAway: '{distance} ኪ.ሜ ርቀት',
    nutritionFacts: 'የምግብ መረጃ',
    wellnessScore: 'የጤና ነጥብ {score}',
    shopAgain: 'እንደገና ይግዙ',
    unifiedWellnessProfile: 'የተዋሃደ የጤና መገለጫ',
    profileWellnessHeadline: 'ምግብ፣ ስሜት፣ እርግዝና፣ መተንፈስ፣ እንቅስቃሴ እና ትኩስነት ተያይዘዋል።',
    viewDashboard: 'ዳሽቦርድ ይመልከቱ',
    orders: 'ትዕዛዞች',
    savedProducts: 'የተቀመጡ ምርቶች',
    noSavedProducts: 'እስካሁን የተቀመጡ ምርቶች የሉም።',
    wellnessTitle: 'ዛሬ እንዴት ይሰማዎታል?',
    wellnessCopy: 'ስሜት፣ የእርግዝና ጤና እና መተንፈስን በአንድ ቀላል ቦታ ይከታተሉ።',
    moodCheckIn: 'የስሜት ምዝገባ',
    pregnancyCoach: 'የእርግዝና አማካሪ',
    breathing: 'መተንፈስ',
    myWellness: 'የእኔ ጤና',
    energy: 'ኃይል',
    sleep: 'እንቅልፍ',
    stress: 'ጭንቀት',
    moodNote: 'ስለ ቀንዎ አጭር ማስታወሻ ይጻፉ...',
    saveMood: 'ስሜት አስቀምጥ',
    currentWeek: 'የአሁኑ ሳምንት',
    week: 'ሳምንት {week}',
    dueDate: 'የመውለጃ ቀን',
    waterToday: 'ዛሬ ውሃ',
    ironToday: 'ዛሬ ብረት',
    todaysGuidance: 'የዛሬ መመሪያ',
    pregnancyGuidance: 'በብረት የበለፀጉ ምግቦችን ይብሉ፣ ውሃ ይጠጡ፣ ከተፈቀደ ቀላል መራመድ ያድርጉ፣ እና አደገኛ ምግቦችን ያስወግዱ።',
    logPregnancy: 'የእርግዝና ሁኔታ ይመዝግቡ',
    recommendedNow: 'አሁን የሚመከር፦',
    streak: 'ተከታታይ',
    lastSession: 'የመጨረሻ ክፍለጊዜ',
    stressReduced: 'ጭንቀት ቀንሷል',
    unifiedWellnessScore: 'የተዋሃደ የጤና ነጥብ',
    wellnessScoreParts: 'ምግብ + ስሜት + እርግዝና + መተንፈስ + ትኩስነት',
    aiSuggestion: 'የAI ምክር',
    mood: 'ስሜት',
    viewHistory: 'ታሪክ ይመልከቱ',
    getAiAdvice: 'የAI ምክር ያግኙ',
    shopWellnessFoods: 'የጤና ምግቦች ይግዙ',
  },
  om: {
    language: 'Afaan',
    navHome: 'Fuula Jalqabaa',
    navMarketplace: 'Gabaa',
    navCoach: 'Gorsaa AI',
    navWellness: 'Fayyaa',
    navFarmer: 'Qonnaan Bulaa',
    navProfile: 'Profaayilii',
    cart: 'Gaarii',
    profile: 'Profaayilii',
    menu: 'Meenuu',
    saveProduct: "Omisha olkaa'i",
    byFarmer: 'kan {name}',
    addToCart: 'Gara gaariitti dabali',
    categoryGrain: 'Midhaan',
    categoryVegetable: 'Kuduraa',
    categoryLegume: 'Atara',
    categoryFruit: 'Muduraa',
    categoryPantry: 'Kuusaa mana',
    trustExcellent: 'baayyee gaarii',
    trustStrong: 'jabaa',
    trustReview: 'ilaalamaa',
    freshExcellent: 'haaraa',
    freshGood: 'gaarii',
    freshFair: 'giddu galeessa',
    landingBadge: 'Gabaa qonnaa gara fayyaatti',
    landingCopy: 'Qonnaan bultoota xixiqqaa Itoophiyaa waliin kallattiin wal qunnami, nyaata naannoo kee jiru irratti hundaa’ee gorsa nyaataa AI argadhu.',
    shopFreshFood: 'Nyaata haaraa bitti',
    askAiCoach: 'Gorsaa AI gaafadhu',
    wellnessHub: 'Wiirtuu fayyaa',
    statProducts: 'Omisha 30',
    statFarmers: 'Qonnaan bultoota 10',
    statDiscovery: 'Argannoo km 20',
    todayNear: 'Har’a naannoo Finfinnee',
    harvestHero: 'Xaafii, spinach, missira fi dammi sa’aatii 48 keessatti sassaabaman.',
    browseNearby: 'Kan dhihoo ilaali',
    aiNutrition: 'Gorsa nyaataa AI',
    verifiedFarmers: 'Qonnaan bultoota mirkanaa’an',
    impactMetrics: 'Safartuu bu’aa',
    workflowCopy: 'Adeemsa hojiirra oolu maatii fayya qabeessaafi galii qonnaan bulaa cimsuuf.',
    advancedWellness: 'Fayyaa sadarkaa ol’aanaa',
    wellnessHeadline: 'Miirri, ulfi, fi tasgabbiin yaadaa amma gorsa nyaataa ni qajeelchu',
    openDashboard: 'Daashboordii bani',
    liveMarketplace: 'Gabaa kallattii',
    freshPicks: 'Filannoo haaraa demoof',
    viewAll: 'Hundaa ilaali',
    valueFarmers: 'Qonnaan bultoonni kallattiin gurguruun gatii caalaa argatu.',
    valueConsumers: 'Bittoonni osoo hin bitin haaraa ta’uu, fageenya, fi amantaa ni argu.',
    valueNutrition: 'Gorsi nyaataa midhaan naannoo gara karoora fayyaatti jijjiira.',
    marketplaceEyebrow: 'Argannoo bakka irratti hundaa’e',
    filters: 'Calaltuu',
    search: 'Barbaadi',
    searchPlaceholder: 'Xaafii, damma...',
    category: 'Ramaddii',
    all: 'Hundaa',
    withinKm: 'Km {distance} keessatti',
    freshness: 'Haaraa {freshness}+',
    maxPrice: 'Gatii ol’aanaa {price} ETB',
    productsFound: 'Omisha {count} argame',
    simulatedLocation: 'Bakka fakkeeffame: Finfinnee',
    cartEmpty: 'Gaariin kee duwwaa dha.',
    browseMarketplace: 'Gabaa ilaali',
    orderSummary: 'Cuunfaa ajajaa',
    subtotal: 'Walitti qabama xiqqaa',
    delivery: 'Geessuu',
    total: 'Waliigala',
    checkout: 'Kaffaltii',
    paymentSuccessful: 'Kaffaltiin Milkaa’eera',
    orderConfirmed: 'Ajajni mirkanaa’e: {id}',
    viewProfile: 'Profaayilii ilaali',
    mockPayment: 'Kaffaltii fakkeessaa',
    mockPaymentCopy: 'Walitti hidhamiinsi kaffaltii dhugaa hin jiru. Adeemsa demo hackathon qofa.',
    payConfirm: 'Kaffaliitii ajaja mirkaneessi',
    backMarketplace: 'Gara gabaatti deebi’i',
    perUnit: '{price} ETB tokkoon {unit}',
    freshnessDetail: 'Haaraa {score}: {label}',
    trustDetail: 'Amanamummaa {score}: {label}',
    harvested: 'Kan sassaabame {date}',
    kmAway: 'Km {distance} fagaata',
    nutritionFacts: 'Odeeffannoo nyaataa',
    wellnessScore: 'Qabxii fayyaa {score}',
    shopAgain: 'Ammas bitti',
    unifiedWellnessProfile: 'Profaayilii fayyaa walitti makame',
    profileWellnessHeadline: 'Nyaanni, miirri, ulfi, hafuura fudhachuun, sochiin, fi haaraa ta’uun walitti hidhataniiru.',
    viewDashboard: 'Daashboordii ilaali',
    orders: 'Ajajoota',
    savedProducts: 'Omishaalee olkaa’aman',
    noSavedProducts: 'Omishni olkaa’ame hanga ammaatti hin jiru.',
    wellnessTitle: 'Har’a akkam sitti dhaga’ama?',
    wellnessCopy: 'Miira, fayyaa ulfaa, fi hafuura fudhachuu bakka salphaa tokko keessatti hordofi.',
    moodCheckIn: 'Galmee Miiraa',
    pregnancyCoach: 'Gorsaa Ulfa',
    breathing: 'Hafuura Fudhachuu',
    myWellness: 'Fayyaa Koo',
    energy: 'Humna',
    sleep: 'Hirriba',
    stress: 'Dhiphina',
    moodNote: 'Waa’ee guyyaa keetii yaadannoo gabaabaa barreessi...',
    saveMood: 'Miira olkaa’i',
    currentWeek: 'Torban ammaa',
    week: 'Torban {week}',
    dueDate: 'Guyyaa da’umsaa',
    waterToday: 'Bishaan har’aa',
    ironToday: 'Ayiraanii har’aa',
    todaysGuidance: 'Qajeelfama har’aa',
    pregnancyGuidance: 'Nyaata ayiraaniin badhaadhe nyaadhu, bishaan dhugi, yoo eeyyamame imala salphaa godhi, nyaata hin amanamne irraa fagaadhu.',
    logPregnancy: 'Haala ulfaa galmeessi',
    recommendedNow: 'Amma kan gorfamu:',
    streak: 'Walduraa duuba',
    lastSession: 'Kutaalee dhumaa',
    stressReduced: 'Dhiphinni hir’ate',
    unifiedWellnessScore: 'Qabxii Fayyaa Walitti Makame',
    wellnessScoreParts: 'Nyaata + miira + ulfa + hafuura + haaraa',
    aiSuggestion: 'Yaada AI',
    mood: 'Miira',
    viewHistory: 'Seenaa ilaali',
    getAiAdvice: 'Gorsa AI argadhu',
    shopWellnessFoods: 'Nyaata fayyaa bitti',
  },
};

const categoryKeys = {
  Grain: 'categoryGrain',
  Vegetable: 'categoryVegetable',
  Legume: 'categoryLegume',
  Fruit: 'categoryFruit',
  Pantry: 'categoryPantry',
};

const LanguageContext = createContext(null);

function format(template, values = {}) {
  return template.replace(/\{(\w+)\}/g, (_, key) => values[key] ?? `{${key}}`);
}

function loadLanguage() {
  try {
    const saved = localStorage.getItem('freshroots:language');
    return translations[saved] ? saved : 'en';
  } catch {
    return 'en';
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(loadLanguage);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (nextLanguage) => {
    if (!translations[nextLanguage]) return;
    setLanguageState(nextLanguage);
    localStorage.setItem('freshroots:language', nextLanguage);
  };

  const value = useMemo(() => {
    const active = translations[language] || translations.en;
    const t = (key, values) => format(active[key] || translations.en[key] || key, values);
    const categoryLabel = (category) => t(categoryKeys[category] || category);
    const freshnessLabel = (score) => {
      if (score >= 80) return t('freshExcellent');
      if (score >= 60) return t('freshGood');
      return t('freshFair');
    };
    const trustLabel = (score) => {
      if (score >= 90) return t('trustExcellent');
      if (score >= 75) return t('trustStrong');
      return t('trustReview');
    };

    return { language, setLanguage, languages, t, categoryLabel, freshnessLabel, trustLabel };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
